### ISSUE TITLE
No word is found in query field

### ISSUE THREAD

**Issue by TTTmath25** [glutanimate/popup-dictionary#50]
could you help me fix this problem please ?
Thank you so much !!!
![2020-07-29](https://user-images.githubusercontent.com/68965415/88868987-7c751880-d1c6-11ea-8679-4d55c1a6d1e3.png)
![2020-07-29 (1)](https://user-images.githubusercontent.com/68965415/88869014-8dbe2500-d1c6-11ea-9fa2-fcf9af72bc03.png)
    
    Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-07-29 09:49:17
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    3 add-ons merged quicker anki explain deletion explain database check ['777545149', 2019-09-26T06:03, 'None', '']
    Add Hyperlink ['318752047', 2020-06-18T06:22, 'None', '']
    AnkiConnect ['2055492159', 2020-07-12T12:54, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-07-12T09:33, 'None', '']
    Edit Field During Review ['1020366288', 2020-05-02T01:15, 'None', '']
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-22T20:10, 'None', '']
    Frozen Fields ['516643804', 2020-02-29T20:12, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-05-02T01:16, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-05-02T01:16, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T10:45, 'None', '']
    Oxford Dictionaries ['1515522458', 2020-01-01T01:28, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T10:32, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2020-07-23T03:25, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T02:11, 'None', '']
    Symbols As You Type ['2040501954', 2020-04-30T07:32, 'None', '']
    True Retention ['613684242', 2017-11-19T12:43, 'None', '']
    Word Query ['775418273', 2017-12-31T09:07, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 1046608507 1374772155 1515522458 153625306 1781298089 1807206748 2040501954 2055492159 295889520 318752047 516643804 594329229 613684242 775418273 777545149 814349176
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by TTTmath25** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-29 09:49:17

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ATD\AppData\Roaming\Anki2\addons21\775418273\prepare.py", line 45, in callback
    return func(obj)
  File "C:\Users\ATD\AppData\Roaming\Anki2\addons21\775418273\query.py", line 135, in query_from_editor_current_field
    editor.saveNow()
TypeError: saveNow() missing 1 required positional argument: 'callback'

**Comment by TTTmath25** [comment]
I have restarted many times. But it doensn't work

**Comment by bkhntrung** [comment]
Mình cũng đang dùng addon này bạn cho mình nick facebook để bàn luận cùng được không?
