### ISSUE TITLE
Not working in Anki 23.10

### ISSUE THREAD

**Issue by orangelover12** [glutanimate/popup-dictionary#85]
#### Problem description

Hello!
First of all, I really like this add-on and I would like to thank you.
My issue is that ANKI 23.10 version came out today and this addon does not work.
I would really appreciate it if you could update it.
Have a good day!

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by aleksejrs** [comment]
It's Anki 23.10.

**Comment by orangelover12** [comment]
Yes, I meant 23.10. I just fixed the post!

**Comment by aleksejrs** [comment]
Thanks, you can fix the title, too.

**Comment by addonico** [comment]
Same issue here. 
![WechatIMG995](https://github.com/glutanimate/popup-dictionary/assets/70325856/acbb6b2d-41b3-4485-ae41-7fd2835400e2)

Version ⁨23.10 (51a10f09)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3

**Comment by ShawnO33** [comment]
Just wanted to provide the debug information, although it probably is easy to reproduce and different on other devices. 
When loading Pop-up Dictionary:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/User/Library/Application Support/Anki2/addons21/popup_dictionary/__init__.py", line 35, in <module>
    from ._addon import *  # noqa: F401, F403
  File "/Users/User/Library/Application Support/Anki2/addons21/popup_dictionary/_addon.py", line 40, in <module>
    from .reviewer import initialize_reviewer
  File "/Users/User/Library/Application Support/Anki2/addons21/popup_dictionary/reviewer.py", line 39, in <module>
    from PyQt5.QtGui import QKeySequence
ModuleNotFoundError: No module named 'PyQt5'

**Comment by Foxy-null** [comment]
I have made this add-on work with PyQt6 and describe how to do it below.

## How to reproduce
- [ ] 1. use [enum converter tool](https://stackoverflow.com/questions/72086632/migrating-to-qt6-pyqt6-what-are-all-the-deprecated-short-form-names-in-qt5) in the addon folder.
- [ ] 2. Replace all "PyQt5" words to "PyQt6". (I recommend using VSCode for bulk replacement.)
- [ ] 3. In "reviewer.py", import QShortcut modules from aqt.qt instead of from QtWidgets
```python
# before

from PyQt6.QtWidgets import QMenu, QShortcut

# after

from PyQt6.QtWidgets import QMenu

...

from aqt.qt import QShortcut

```

~~I have previously customized the code for this add-on file myself, so I apologize if this fix does not help.~~

( Edit: or just download patched addon file from [here](https://github.com/Foxy-null/popup-dictionary-23.10/releases/tag/23.10) )

**Comment by Foxy-null** [comment]
I checked that above procedures work with original pop-up dictionary code. I'll create pull request for this soon.

**Comment by Foxy-null** [comment]
Seems like it's already available as Patreon content.

[URL](https://www.patreon.com/login?ru=%2Fposts%2Fpop-up-for-anki-95606593%3Fimmediate_pledge_flow%3Dtrue)
